### ISSUE TITLE
Good current code for unbalanced OT?

### ISSUE THREAD

**Issue by jacksonloper** [lchizat/optimal-transport#2]
Hi!  Jackson Loper here from Columbia University, working on domain adaptation for single cell RNA.  

I noticed this code hasn't been updated in awhile.  Is there a version of these ideas that is being actively maintained?  Is there any variant of these ideas that has reached sufficient stability to be included in, e.g., Python Optimal Transport?  If you had to solve an unbalanced OT problem tomorrow, what code would you use?

Many thanks.

**Comment by lchizat** [comment]
Dear Jackson,
Indeed, my code is not maintained and written in a deprecated version of
Julia (I will add a warning).
Apparently Python Optimal Transport does not have an implementation of
unbalanced OT.
I would suggest you to look at this Matlab code by Gabriel Peyré:
https://github.com/gpeyre/2017-MCOM-unbalanced-ot that contains an
implementation
of a version of unbalanced OT
<https://github.com/gpeyre/2017-MCOM-unbalanced-ot/blob/master/matlab/sinkhorn_log.m>
.
For performance critical applications, there is the GeomLoss
<https://www.kernel-operations.io/geomloss/index.html> package being
written by a colleague of mine (alpha version so far) which contains an
implementation of unbalanced OT
<https://www.kernel-operations.io/geomloss/_auto_examples/optimal_transport/plot_optimal_transport_labels.html#unbalanced-optimal-transport>
.
If I had to solve unbalanced OT with entropic regularization tomorrow, I
would probably code it from scratch (my bias is that I do not often use
code for applications).

Thanks for your interest, and sorry for the inconvenience.



Le lun. 13 mai 2019 à 05:17, Jackson Loper <notifications@github.com> a
écrit :

**Comment by jacksonloper** [comment]
I'll take a look!  Many thanks!
